### ISSUE TITLE
Sprach-Filter funktioniert nicht mehr

### ISSUE THREAD

**Issue by jdaehne** [sscWhitevision/dor_sw#15]
[![Screenshot_2022-10-19_07-27-30.png](https://mrkr.io/s/634fa6e272e6c4fcd0b5aa87/2)](https://mrkr.io/s/634fa6e272e6c4fcd0b5aa87/0)

Hängt das eventuell mit der Funktion des schließens zusammen. Das müssten wir dann anders lösen und eventuell einfach mit einem versteckten Overlay was hinter dem Sprachwechsler liegt und über allem anderen. Lass uns das gerne gleich zusammen machen.

---

**Reported by:** Jan Dähne (jan.daehne@quadro-system.de)

**Source URL:** [https://sw.whitevision-hosting.de/#](https://sw.whitevision-hosting.de/#)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/634fa6e272e6c4fcd0b5aa8a_334f6bf264d64f95)

**Console:** [📃  0 logs](https://app.marker.io/i/634fa6e272e6c4fcd0b5aa8a_334f6bf264d64f95?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 106.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3440 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1698 x 1178</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by meeheee** [comment]
Da haben die die Klassen an den li`s gefehlt. Habe ich schon gefixt

**Comment by jdaehne** [comment]
🤖 [Marker.io bot](https://app.marker.io/i/634fa6e272e6c4fcd0b5aa8a_334f6bf264d64f95) - This issue was marked as **✅ Resolved** by **Michael Wachter (michael.wachter@quadro-system.de)** in Marker.io
