### ISSUE TITLE
Seitentitel

### ISSUE THREAD

**Issue by jdaehne** [sscWhitevision/dor_sw#5]
[![Screenshot_2022-10-17_13-45-56.png](https://mrkr.io/s/634d5c94fa6857e22d60e4d6/2)](https://mrkr.io/s/634d5c94fa6857e22d60e4d6/0)

Der Seitentitel ist immer Küzel in Großbuchstzaben - Projektname

Also DOR_SW - Shinewing

---

**Reported by:** Jan Dähne (jan.daehne@quadro-system.de)

**Source URL:** [https://sw.whitevision-hosting.de/](https://sw.whitevision-hosting.de/)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/634d5c94fa6857e22d60e4d9_6162faf61fc4add9)

**Console:** [📃  0 logs](https://app.marker.io/i/634d5c94fa6857e22d60e4d9_6162faf61fc4add9?activePane=console)

<table><tr><td><strong>Device type</strong></td><td>desktop</td></tr><tr><td><strong>Browser</strong></td><td>Chrome 105.0.0.0</td></tr><tr><td><strong>Screen Size</strong></td><td>3440 x 1440</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.6.0</td></tr><tr><td><strong>Viewport Size</strong></td><td>1671 x 895</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;1x</td></tr></table>

**Comment by meeheee** [comment]
Um welchen Titel geht es, der Titel der im Tab steht?

**Comment by jdaehne** [comment]
Ja genau. <title>...</title>
